"""Transaction outcomes with a closed set of fields, never payloads or exception text."""

import json
import logging
from functools import wraps
from hashlib import sha256
from time import perf_counter

from sqlalchemy import event
from sqlalchemy.exc import SQLAlchemyError
from sqlalchemy.orm import Session

from jobintel.openai_transport import ProviderError

LOGGER = logging.getLogger("jobintel.outcomes")
PENDING = "jobintel_outcomes"
PROVIDER_CODES = {
    "timeout",
    "quota",
    "rate_limit",
    "provider_failure",
    "refusal",
    "invalid_evidence",
    "malformed_json",
    "invalid_schema",
    "incomplete_response",
}


def error_code(error):
    if isinstance(error, SQLAlchemyError):
        return "database_error"
    if isinstance(error, ProviderError):
        return error.code if error.code in PROVIDER_CODES else "provider_failure"
    if isinstance(error, KeyError):
        return "not_found"
    if isinstance(error, ValueError):
        return "validation_error"
    return "operation_failure"


def outcome(operation):
    def decorate(function):
        @wraps(function)
        def observed(self, *args, **kwargs):
            record = {"operation": operation, "error_code": None}
            if args and isinstance(args[0], str):
                record["subject_sha256"] = sha256(args[0].encode()).hexdigest()
            transaction = (
                self.session.get_nested_transaction()
                or self.session.get_transaction()
                or self.session.begin()
            )
            self.session.info.setdefault(PENDING, {}).setdefault(transaction, []).append(record)
            started = perf_counter()
            try:
                result = function(self, *args, **kwargs)
                # These identifiers are generated by storage, not provider/source text.
                if isinstance(result, dict):
                    for key in ("run_id", "snapshot_id", "profile_revision_id", "match_run_id"):
                        if key in result:
                            record[key] = result[key]
                return result
            except Exception as error:
                record["error_code"] = error_code(error)
                raise
            finally:
                record["elapsed_ms"] = round((perf_counter() - started) * 1000, 3)

        return observed

    return decorate


def publish(session, transaction, committed):
    for pending in session.info.get(PENDING, {}).pop(transaction, []):
        record = {
            **pending,
            "outcome": "committed" if committed else "rolled_back",
            "error_code": None if committed else pending["error_code"] or "transaction_rollback",
        }
        LOGGER.info(json.dumps(record, sort_keys=True), extra={"jobintel_outcome": record})


@event.listens_for(Session, "after_commit")
def committed(session):
    nested = session.get_nested_transaction()
    if nested is not None:
        # Savepoint release is not a durable commit of the outer operation.
        buffers = session.info.get(PENDING, {})
        buffers.setdefault(nested.parent, []).extend(buffers.pop(nested, []))
    else:
        publish(session, session.get_transaction(), True)


@event.listens_for(Session, "after_transaction_end")
def ended(session, transaction):
    # Covers savepoint rollback and closing after an unexpected, unhandled failure.
    publish(session, transaction, False)
