services:
  migrate:
    build:
      context: .
      dockerfile: Dockerfile.offline
  api:
    build:
      context: .
      dockerfile: Dockerfile.offline
  responses-emulator:
    profiles: [contract-test]
    build:
      context: .
      dockerfile: Dockerfile.offline
