"""initial auditable storage"""

import sqlalchemy as sa

from alembic import op

revision = "e44d9dbe9d1d"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "candidate_evidence",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("profile_id", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_candidate_evidence_profile_id"), "candidate_evidence", ["profile_id"], unique=False
    )
    op.create_table(
        "evaluation_runs",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "jobs",
        sa.Column("job_id", sa.String(length=64), nullable=False),
        sa.Column("identity", sa.String(length=500), nullable=False),
        sa.Column("official_url", sa.Text(), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("job_id"),
        sa.UniqueConstraint("identity"),
        sa.UniqueConstraint("official_url"),
    )
    op.create_table(
        "skills",
        sa.Column("canonical", sa.String(length=200), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("canonical"),
    )
    op.create_table(
        "posting_snapshots",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("job_id", sa.String(length=64), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("fetched_at", sa.String(length=40), nullable=False),
        sa.Column("raw_text", sa.Text(), nullable=False),
        sa.Column("clean_text", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("fetch_status", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.job_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_posting_snapshots_job_id"), "posting_snapshots", ["job_id"], unique=False
    )
    op.create_table(
        "extraction_runs",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("snapshot_id", sa.String(length=32), nullable=False),
        sa.Column("configuration", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["posting_snapshots.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_extraction_runs_snapshot_id"), "extraction_runs", ["snapshot_id"], unique=False
    )
    op.create_table(
        "requirements",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("run_id", sa.String(length=32), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["extraction_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_requirements_run_id"), "requirements", ["run_id"], unique=False)
    op.create_table(
        "matches",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("requirement_id", sa.String(length=32), nullable=False),
        sa.Column("candidate_evidence_id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["candidate_evidence_id"],
            ["candidate_evidence.id"],
        ),
        sa.ForeignKeyConstraint(
            ["requirement_id"],
            ["requirements.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_matches_requirement_id"), "matches", ["requirement_id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_matches_requirement_id"), table_name="matches")
    op.drop_table("matches")
    op.drop_index(op.f("ix_requirements_run_id"), table_name="requirements")
    op.drop_table("requirements")
    op.drop_index(op.f("ix_extraction_runs_snapshot_id"), table_name="extraction_runs")
    op.drop_table("extraction_runs")
    op.drop_index(op.f("ix_posting_snapshots_job_id"), table_name="posting_snapshots")
    op.drop_table("posting_snapshots")
    op.drop_table("skills")
    op.drop_table("jobs")
    op.drop_table("evaluation_runs")
    op.drop_index(op.f("ix_candidate_evidence_profile_id"), table_name="candidate_evidence")
    op.drop_table("candidate_evidence")
    # ### end Alembic commands ###
